import { ClipboardList, Minus, Plus, Trash2, X } from 'lucide-react'
import { getProduct } from '../../data/products'
import { useRequest } from './RequestContext'
import { Button, IconButton } from '../../shared/ui'

export function RequestDrawer() {
  const { items, isDrawerOpen, setDrawerOpen, updateQuantity, removeItem, totalItems } = useRequest()
  if (!isDrawerOpen) return null
  return <div className="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true" aria-label="Request summary"><button aria-label="Close request summary" className="absolute inset-0 cursor-default bg-black/40" onClick={() => setDrawerOpen(false)} /><aside className="relative flex h-full w-full max-w-md flex-col bg-white shadow-2xl">
    <div className="flex items-center justify-between border-b border-line/50 p-5"><div><p className="eyebrow">Your list</p><h2 className="font-primary text-xl font-bold text-forest">Request Summary</h2></div><IconButton label="Close request summary" onClick={() => setDrawerOpen(false)} icon={<X />} /></div>
    {items.length === 0 ? <div className="flex flex-1 flex-col items-center justify-center px-8 text-center"><ClipboardList size={42} className="mb-4 text-moss" /><h3 className="font-primary  text-lg font-primary text-forest">Your request is empty</h3><p className="mt-2 text-sm text-slate-600">Add the provisions you need, then send one clear list to our team.</p><Button href="/categories" className="mt-6" onClick={() => setDrawerOpen(false)}>Browse provisions</Button></div> : <><ul className="flex-1 divide-y divide-line/40 overflow-y-auto">{items.map((item) => { const product = getProduct(item.productId); if (!product) return null; return <li key={`${item.productId}-${item.measurement}`} className="flex gap-3 p-5"><img src={product.image} alt="" className="h-16 w-16 rounded-lg object-cover" /><div className="min-w-0 flex-1"><h3 className="font-bold text-forest">{product.name}</h3><p className="mt-0.5 text-sm text-slate-600">{item.measurement}</p><div className="mt-3 flex items-center gap-2"><IconButton label={`Decrease ${product.name}`} onClick={() => updateQuantity(item.productId, item.measurement, item.quantity - 1)} variant="outline" size="sm" className="text-forest" icon={<Minus size={14} />} /><span className="w-6 text-center text-sm font-bold">{item.quantity}</span><IconButton label={`Increase ${product.name}`} onClick={() => updateQuantity(item.productId, item.measurement, item.quantity + 1)} variant="outline" size="sm" className="text-forest" icon={<Plus size={14} />} /><IconButton label={`Remove ${product.name}`} onClick={() => removeItem(item.productId, item.measurement)} variant="danger" size="sm" className="ml-auto" icon={<Trash2 size={17} />} /></div></div></li> })}</ul><div className="border-t border-line/50 p-5"><p className="mb-4 text-sm text-slate-600">{totalItems} {totalItems === 1 ? 'item' : 'items'} ready to send</p><Button href="/request" fullWidth onClick={() => setDrawerOpen(false)}>Continue to details</Button></div></>}
  </aside></div>
}
